title: Blog
author: LJW27
description: This blog records work experience.

markdown: kramdown
highlighter: rouge
permalink: /:title

url: 'http://ljw27.github.io'
baseurl:

sass:
  sass_dir: public/css
  style: :compressed
